//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lab3/", ConfigurationName="PSQLServiceReference.PrintToPSQLWebService")]
    public interface PrintToPSQLWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab3/PrintToPSQLWebService/printToPostgreSQLRequest", ReplyAction="http://lab3/PrintToPSQLWebService/printToPostgreSQLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string printToPostgreSQL(trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.firstNFLine arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lab3/PrintToPSQLWebService/printToPostgreSQLRequest", ReplyAction="http://lab3/PrintToPSQLWebService/printToPostgreSQLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> printToPostgreSQLAsync(trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.firstNFLine arg0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lab3/")]
    public partial class firstNFLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cat_idField;
        
        private string cat_nameField;
        
        private string colorField;
        
        private int breed_idField;
        
        private string breedField;
        
        private int place_idField;
        
        private string place_nameField;
        
        private string typeField;
        
        private int food_idField;
        
        private string food_nameField;
        
        private int priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cat_id {
            get {
                return this.cat_idField;
            }
            set {
                this.cat_idField = value;
                this.RaisePropertyChanged("cat_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cat_name {
            get {
                return this.cat_nameField;
            }
            set {
                this.cat_nameField = value;
                this.RaisePropertyChanged("cat_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int breed_id {
            get {
                return this.breed_idField;
            }
            set {
                this.breed_idField = value;
                this.RaisePropertyChanged("breed_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
                this.RaisePropertyChanged("breed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int place_id {
            get {
                return this.place_idField;
            }
            set {
                this.place_idField = value;
                this.RaisePropertyChanged("place_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string place_name {
            get {
                return this.place_nameField;
            }
            set {
                this.place_nameField = value;
                this.RaisePropertyChanged("place_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int food_id {
            get {
                return this.food_idField;
            }
            set {
                this.food_idField = value;
                this.RaisePropertyChanged("food_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string food_name {
            get {
                return this.food_nameField;
            }
            set {
                this.food_nameField = value;
                this.RaisePropertyChanged("food_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrintToPSQLWebServiceChannel : trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.PrintToPSQLWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintToPSQLWebServiceClient : System.ServiceModel.ClientBase<trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.PrintToPSQLWebService>, trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.PrintToPSQLWebService {
        
        public PrintToPSQLWebServiceClient() {
        }
        
        public PrintToPSQLWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintToPSQLWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintToPSQLWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintToPSQLWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string printToPostgreSQL(trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.firstNFLine arg0) {
            return base.Channel.printToPostgreSQL(arg0);
        }
        
        public System.Threading.Tasks.Task<string> printToPostgreSQLAsync(trrp_lab3_thank_god_its_finally_csharp.PSQLServiceReference.firstNFLine arg0) {
            return base.Channel.printToPostgreSQLAsync(arg0);
        }
    }
}
