package com.company;// generated by tscfg
// source: src/main/resources/application.conf.template

import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;

import java.io.File;

public class AppConfig {
    public final SocketServer socketServer;
    public final MessageQueueServer messageQueueServer;

    public AppConfig(com.typesafe.config.Config c) {
        final $TsCfgValidator $tsCfgValidator = new $TsCfgValidator();
        final String parentPath = "";
        this.socketServer =
                c.hasPathOrNull("socketServer")
                        ? new SocketServer(
                        c.getConfig("socketServer"), parentPath + "socketServer.", $tsCfgValidator)
                        : new SocketServer(
                        com.typesafe.config.ConfigFactory.parseString("socketServer{}"),
                        parentPath + "socketServer.",
                        $tsCfgValidator);
        this.messageQueueServer =
                c.hasPathOrNull("messageQueueServer")
                        ? new MessageQueueServer(
                        c.getConfig("messageQueueServer"),
                        parentPath + "messageQueueServer.",
                        $tsCfgValidator)
                        : new MessageQueueServer(
                        com.typesafe.config.ConfigFactory.parseString("messageQueueServer{}"),
                        parentPath + "messageQueueServer.",
                        $tsCfgValidator);
        $tsCfgValidator.validate();
    }

    public static AppConfig load() {
        Config config = ConfigFactory.parseFile(new File("application.conf")).withFallback(ConfigFactory.load());
        return new AppConfig(config);
    }

    public static class SocketServer {
        public final String host;
        public final int port;

        public SocketServer(
                com.typesafe.config.Config c,
                String parentPath,
                $TsCfgValidator $tsCfgValidator) {
            this.host = $_reqStr(parentPath, c, "host", $tsCfgValidator);
            this.port = $_reqInt(parentPath, c, "port", $tsCfgValidator);
        }

        private static int $_reqInt(
                String parentPath,
                com.typesafe.config.Config c,
                String path,
                $TsCfgValidator $tsCfgValidator) {
            if (c == null) return 0;
            try {
                return c.getInt(path);
            } catch (com.typesafe.config.ConfigException e) {
                $tsCfgValidator.addBadPath(parentPath + path, e);
                return 0;
            }
        }

        private static String $_reqStr(
                String parentPath,
                com.typesafe.config.Config c,
                String path,
                $TsCfgValidator $tsCfgValidator) {
            if (c == null) return null;
            try {
                return c.getString(path);
            } catch (com.typesafe.config.ConfigException e) {
                $tsCfgValidator.addBadPath(parentPath + path, e);
                return null;
            }
        }
    }

    public static class MessageQueueServer {
        public final String host;
        public final String password;
        public final int port;
        public final String username;

        public MessageQueueServer(
                com.typesafe.config.Config c,
                String parentPath,
                $TsCfgValidator $tsCfgValidator) {
            this.host = $_reqStr(parentPath, c, "host", $tsCfgValidator);
            this.password = $_reqStr(parentPath, c, "password", $tsCfgValidator);
            this.port = c.hasPathOrNull("port") ? c.getInt("port") : 5672;
            this.username = $_reqStr(parentPath, c, "username", $tsCfgValidator);
        }

        private static String $_reqStr(
                String parentPath,
                com.typesafe.config.Config c,
                String path,
                $TsCfgValidator $tsCfgValidator) {
            if (c == null) return null;
            try {
                return c.getString(path);
            } catch (com.typesafe.config.ConfigException e) {
                $tsCfgValidator.addBadPath(parentPath + path, e);
                return null;
            }
        }
    }

    private static final class $TsCfgValidator {
        private final java.util.List<String> badPaths = new java.util.ArrayList<>();

        void addBadPath(String path, com.typesafe.config.ConfigException e) {
            badPaths.add("'" + path + "': " + e.getClass().getName() + "(" + e.getMessage() + ")");
        }

        void validate() {
            if (!badPaths.isEmpty()) {
                StringBuilder sb = new StringBuilder("Invalid configuration:");
                for (String path : badPaths) {
                    sb.append("\n    ").append(path);
                }
                throw new com.typesafe.config.ConfigException(sb.toString()) {
                };
            }
        }
    }
}
